project '../SlackTest.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SlackTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlackTest
  pod 'FeedbackSlack', :path => '../'

  target 'SlackTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlackTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
